import 'package:flutter/widgets.dart';
import 'package:shadcn_ui/src/theme/color_scheme/base.dart';

/// The shadcn/ui `mist` colour scheme.
///
/// Generated from shadcn/ui's `registry/themes.ts`, converting each OKLCH
/// value to sRGB.
@immutable
class ShadMistColorScheme extends ShadColorScheme {
  const ShadMistColorScheme({
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    super.chart1,
    super.chart2,
    super.chart3,
    super.chart4,
    super.chart5,
    super.sidebar,
    super.sidebarForeground,
    super.sidebarPrimary,
    super.sidebarPrimaryForeground,
    super.sidebarAccent,
    super.sidebarAccentForeground,
    super.sidebarBorder,
    super.sidebarRing,
    super.custom,
  });

  const ShadMistColorScheme.light({
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff090b0c),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff090b0c),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff090b0c),
    super.primary = const Color(0xff161b1d),
    super.primaryForeground = const Color(0xfff9fbfb),
    super.secondary = const Color(0xfff1f3f3),
    super.secondaryForeground = const Color(0xff161b1d),
    super.muted = const Color(0xfff1f3f3),
    super.mutedForeground = const Color(0xff67787c),
    super.accent = const Color(0xfff1f3f3),
    super.accentForeground = const Color(0xff161b1d),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xfff9fbfb),
    super.border = const Color(0xffe3e7e8),
    super.input = const Color(0xffe3e7e8),
    super.ring = const Color(0xff9ca8ab),
    super.selection = const Color(0x33161b1d),
    super.chart1 = const Color(0xffd0d6d8),
    super.chart2 = const Color(0xff67787c),
    super.chart3 = const Color(0xff4b585b),
    super.chart4 = const Color(0xff394447),
    super.chart5 = const Color(0xff22292b),
    super.sidebar = const Color(0xfff9fbfb),
    super.sidebarForeground = const Color(0xff090b0c),
    super.sidebarPrimary = const Color(0xff161b1d),
    super.sidebarPrimaryForeground = const Color(0xfff9fbfb),
    super.sidebarAccent = const Color(0xfff1f3f3),
    super.sidebarAccentForeground = const Color(0xff161b1d),
    super.sidebarBorder = const Color(0xffe3e7e8),
    super.sidebarRing = const Color(0xff9ca8ab),
    super.custom,
  });

  const ShadMistColorScheme.dark({
    super.background = const Color(0xff090b0c),
    super.foreground = const Color(0xfff9fbfb),
    super.card = const Color(0xff161b1d),
    super.cardForeground = const Color(0xfff9fbfb),
    super.popover = const Color(0xff161b1d),
    super.popoverForeground = const Color(0xfff9fbfb),
    super.primary = const Color(0xffe3e7e8),
    super.primaryForeground = const Color(0xff161b1d),
    super.secondary = const Color(0xff22292b),
    super.secondaryForeground = const Color(0xfff9fbfb),
    super.muted = const Color(0xff22292b),
    super.mutedForeground = const Color(0xff9ca8ab),
    super.accent = const Color(0xff22292b),
    super.accentForeground = const Color(0xfff9fbfb),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff161b1d),
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff67787c),
    super.selection = const Color(0x33e3e7e8),
    super.chart1 = const Color(0xffd0d6d8),
    super.chart2 = const Color(0xff67787c),
    super.chart3 = const Color(0xff4b585b),
    super.chart4 = const Color(0xff394447),
    super.chart5 = const Color(0xff22292b),
    super.sidebar = const Color(0xff161b1d),
    super.sidebarForeground = const Color(0xfff9fbfb),
    super.sidebarPrimary = const Color(0xff1447e6),
    super.sidebarPrimaryForeground = const Color(0xfff9fbfb),
    super.sidebarAccent = const Color(0xff22292b),
    super.sidebarAccentForeground = const Color(0xfff9fbfb),
    super.sidebarBorder = const Color(0x1affffff),
    super.sidebarRing = const Color(0xff67787c),
    super.custom,
  });
}
