import 'package:flutter/widgets.dart';
import 'package:shad/src/theme/color_scheme/base.dart';

/// The shadcn/ui `neutral` colour scheme.
///
/// Generated from shadcn/ui's `registry/themes.ts`, converting each OKLCH
/// value to sRGB.
@immutable
class ShadNeutralColorScheme extends ShadColorScheme {
  const ShadNeutralColorScheme({
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    super.chart1,
    super.chart2,
    super.chart3,
    super.chart4,
    super.chart5,
    super.sidebar,
    super.sidebarForeground,
    super.sidebarPrimary,
    super.sidebarPrimaryForeground,
    super.sidebarAccent,
    super.sidebarAccentForeground,
    super.sidebarBorder,
    super.sidebarRing,
    super.custom,
  });

  const ShadNeutralColorScheme.light({
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0a0a0a),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0a0a0a),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0a0a0a),
    super.primary = const Color(0xff171717),
    super.primaryForeground = const Color(0xfffafafa),
    super.secondary = const Color(0xfff5f5f5),
    super.secondaryForeground = const Color(0xff171717),
    super.muted = const Color(0xfff5f5f5),
    super.mutedForeground = const Color(0xff737373),
    super.accent = const Color(0xfff5f5f5),
    super.accentForeground = const Color(0xff171717),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xfffafafa),
    super.border = const Color(0xffe5e5e5),
    super.input = const Color(0xffe5e5e5),
    super.ring = const Color(0xffa1a1a1),
    super.selection = const Color(0x33171717),
    super.chart1 = const Color(0xffd4d4d4),
    super.chart2 = const Color(0xff737373),
    super.chart3 = const Color(0xff525252),
    super.chart4 = const Color(0xff404040),
    super.chart5 = const Color(0xff262626),
    super.sidebar = const Color(0xfffafafa),
    super.sidebarForeground = const Color(0xff0a0a0a),
    super.sidebarPrimary = const Color(0xff171717),
    super.sidebarPrimaryForeground = const Color(0xfffafafa),
    super.sidebarAccent = const Color(0xfff5f5f5),
    super.sidebarAccentForeground = const Color(0xff171717),
    super.sidebarBorder = const Color(0xffe5e5e5),
    super.sidebarRing = const Color(0xffa1a1a1),
    super.custom,
  });

  const ShadNeutralColorScheme.dark({
    super.background = const Color(0xff0a0a0a),
    super.foreground = const Color(0xfffafafa),
    super.card = const Color(0xff171717),
    super.cardForeground = const Color(0xfffafafa),
    super.popover = const Color(0xff171717),
    super.popoverForeground = const Color(0xfffafafa),
    super.primary = const Color(0xffe5e5e5),
    super.primaryForeground = const Color(0xff171717),
    super.secondary = const Color(0xff262626),
    super.secondaryForeground = const Color(0xfffafafa),
    super.muted = const Color(0xff262626),
    super.mutedForeground = const Color(0xffa1a1a1),
    super.accent = const Color(0xff262626),
    super.accentForeground = const Color(0xfffafafa),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff171717),
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff737373),
    super.selection = const Color(0x33e5e5e5),
    super.chart1 = const Color(0xffd4d4d4),
    super.chart2 = const Color(0xff737373),
    super.chart3 = const Color(0xff525252),
    super.chart4 = const Color(0xff404040),
    super.chart5 = const Color(0xff262626),
    super.sidebar = const Color(0xff171717),
    super.sidebarForeground = const Color(0xfffafafa),
    super.sidebarPrimary = const Color(0xff1447e6),
    super.sidebarPrimaryForeground = const Color(0xfffafafa),
    super.sidebarAccent = const Color(0xff262626),
    super.sidebarAccentForeground = const Color(0xfffafafa),
    super.sidebarBorder = const Color(0x1affffff),
    super.sidebarRing = const Color(0xff737373),
    super.custom,
  });
}
