import 'package:flutter/widgets.dart';
import 'package:shadcn_ui/src/theme/color_scheme/base.dart';

/// The shadcn/ui `olive` colour scheme.
///
/// Generated from shadcn/ui's `registry/themes.ts`, converting each OKLCH
/// value to sRGB.
@immutable
class ShadOliveColorScheme extends ShadColorScheme {
  const ShadOliveColorScheme({
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    super.chart1,
    super.chart2,
    super.chart3,
    super.chart4,
    super.chart5,
    super.sidebar,
    super.sidebarForeground,
    super.sidebarPrimary,
    super.sidebarPrimaryForeground,
    super.sidebarAccent,
    super.sidebarAccentForeground,
    super.sidebarBorder,
    super.sidebarRing,
    super.custom,
  });

  const ShadOliveColorScheme.light({
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0c0c09),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0c0c09),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0c0c09),
    super.primary = const Color(0xff1d1d16),
    super.primaryForeground = const Color(0xfffbfbf9),
    super.secondary = const Color(0xfff4f4f0),
    super.secondaryForeground = const Color(0xff1d1d16),
    super.muted = const Color(0xfff4f4f0),
    super.mutedForeground = const Color(0xff7c7c67),
    super.accent = const Color(0xfff4f4f0),
    super.accentForeground = const Color(0xff1d1d16),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xfffbfbf9),
    super.border = const Color(0xffe8e8e3),
    super.input = const Color(0xffe8e8e3),
    super.ring = const Color(0xffabab9c),
    super.selection = const Color(0x331d1d16),
    super.chart1 = const Color(0xffd8d8d0),
    super.chart2 = const Color(0xff7c7c67),
    super.chart3 = const Color(0xff5b5b4b),
    super.chart4 = const Color(0xff474739),
    super.chart5 = const Color(0xff2b2b22),
    super.sidebar = const Color(0xfffbfbf9),
    super.sidebarForeground = const Color(0xff0c0c09),
    super.sidebarPrimary = const Color(0xff1d1d16),
    super.sidebarPrimaryForeground = const Color(0xfffbfbf9),
    super.sidebarAccent = const Color(0xfff4f4f0),
    super.sidebarAccentForeground = const Color(0xff1d1d16),
    super.sidebarBorder = const Color(0xffe8e8e3),
    super.sidebarRing = const Color(0xffabab9c),
    super.custom,
  });

  const ShadOliveColorScheme.dark({
    super.background = const Color(0xff0c0c09),
    super.foreground = const Color(0xfffbfbf9),
    super.card = const Color(0xff1d1d16),
    super.cardForeground = const Color(0xfffbfbf9),
    super.popover = const Color(0xff1d1d16),
    super.popoverForeground = const Color(0xfffbfbf9),
    super.primary = const Color(0xffe8e8e3),
    super.primaryForeground = const Color(0xff1d1d16),
    super.secondary = const Color(0xff2b2b22),
    super.secondaryForeground = const Color(0xfffbfbf9),
    super.muted = const Color(0xff2b2b22),
    super.mutedForeground = const Color(0xffabab9c),
    super.accent = const Color(0xff2b2b22),
    super.accentForeground = const Color(0xfffbfbf9),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff1d1d16),
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff7c7c67),
    super.selection = const Color(0x33e8e8e3),
    super.chart1 = const Color(0xffd8d8d0),
    super.chart2 = const Color(0xff7c7c67),
    super.chart3 = const Color(0xff5b5b4b),
    super.chart4 = const Color(0xff474739),
    super.chart5 = const Color(0xff2b2b22),
    super.sidebar = const Color(0xff1d1d16),
    super.sidebarForeground = const Color(0xfffbfbf9),
    super.sidebarPrimary = const Color(0xff1447e6),
    super.sidebarPrimaryForeground = const Color(0xfffbfbf9),
    super.sidebarAccent = const Color(0xff2b2b22),
    super.sidebarAccentForeground = const Color(0xfffbfbf9),
    super.sidebarBorder = const Color(0x1affffff),
    super.sidebarRing = const Color(0xff7c7c67),
    super.custom,
  });
}
