import 'package:flutter/widgets.dart';
import 'package:shadcn_ui/src/theme/color_scheme/base.dart';

/// The shadcn/ui `stone` colour scheme.
///
/// Generated from shadcn/ui's `registry/themes.ts`, converting each OKLCH
/// value to sRGB.
@immutable
class ShadStoneColorScheme extends ShadColorScheme {
  const ShadStoneColorScheme({
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    super.chart1,
    super.chart2,
    super.chart3,
    super.chart4,
    super.chart5,
    super.sidebar,
    super.sidebarForeground,
    super.sidebarPrimary,
    super.sidebarPrimaryForeground,
    super.sidebarAccent,
    super.sidebarAccentForeground,
    super.sidebarBorder,
    super.sidebarRing,
    super.custom,
  });

  const ShadStoneColorScheme.light({
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0c0a09),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0c0a09),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0c0a09),
    super.primary = const Color(0xff1c1917),
    super.primaryForeground = const Color(0xfffafaf9),
    super.secondary = const Color(0xfff5f5f4),
    super.secondaryForeground = const Color(0xff1c1917),
    super.muted = const Color(0xfff5f5f4),
    super.mutedForeground = const Color(0xff79716b),
    super.accent = const Color(0xfff5f5f4),
    super.accentForeground = const Color(0xff1c1917),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xfffafaf9),
    super.border = const Color(0xffe7e5e4),
    super.input = const Color(0xffe7e5e4),
    super.ring = const Color(0xffa6a09b),
    super.selection = const Color(0x331c1917),
    super.chart1 = const Color(0xffd6d3d1),
    super.chart2 = const Color(0xff79716b),
    super.chart3 = const Color(0xff57534d),
    super.chart4 = const Color(0xff44403b),
    super.chart5 = const Color(0xff292524),
    super.sidebar = const Color(0xfffafaf9),
    super.sidebarForeground = const Color(0xff0c0a09),
    super.sidebarPrimary = const Color(0xff1c1917),
    super.sidebarPrimaryForeground = const Color(0xfffafaf9),
    super.sidebarAccent = const Color(0xfff5f5f4),
    super.sidebarAccentForeground = const Color(0xff1c1917),
    super.sidebarBorder = const Color(0xffe7e5e4),
    super.sidebarRing = const Color(0xffa6a09b),
    super.custom,
  });

  const ShadStoneColorScheme.dark({
    super.background = const Color(0xff0c0a09),
    super.foreground = const Color(0xfffafaf9),
    super.card = const Color(0xff1c1917),
    super.cardForeground = const Color(0xfffafaf9),
    super.popover = const Color(0xff1c1917),
    super.popoverForeground = const Color(0xfffafaf9),
    super.primary = const Color(0xffe7e5e4),
    super.primaryForeground = const Color(0xff1c1917),
    super.secondary = const Color(0xff292524),
    super.secondaryForeground = const Color(0xfffafaf9),
    super.muted = const Color(0xff292524),
    super.mutedForeground = const Color(0xffa6a09b),
    super.accent = const Color(0xff292524),
    super.accentForeground = const Color(0xfffafaf9),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff1c1917),
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff79716b),
    super.selection = const Color(0x33e7e5e4),
    super.chart1 = const Color(0xffd6d3d1),
    super.chart2 = const Color(0xff79716b),
    super.chart3 = const Color(0xff57534d),
    super.chart4 = const Color(0xff44403b),
    super.chart5 = const Color(0xff292524),
    super.sidebar = const Color(0xff1c1917),
    super.sidebarForeground = const Color(0xfffafaf9),
    super.sidebarPrimary = const Color(0xff1447e6),
    super.sidebarPrimaryForeground = const Color(0xfffafaf9),
    super.sidebarAccent = const Color(0xff292524),
    super.sidebarAccentForeground = const Color(0xfffafaf9),
    super.sidebarBorder = const Color(0x1affffff),
    super.sidebarRing = const Color(0xff79716b),
    super.custom,
  });
}
