import 'package:flutter/widgets.dart';
import 'package:shad/src/theme/color_scheme/base.dart';

/// The shadcn/ui `taupe` colour scheme.
///
/// Generated from shadcn/ui's `registry/themes.ts`, converting each OKLCH
/// value to sRGB.
@immutable
class ShadTaupeColorScheme extends ShadColorScheme {
  const ShadTaupeColorScheme({
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    super.chart1,
    super.chart2,
    super.chart3,
    super.chart4,
    super.chart5,
    super.sidebar,
    super.sidebarForeground,
    super.sidebarPrimary,
    super.sidebarPrimaryForeground,
    super.sidebarAccent,
    super.sidebarAccentForeground,
    super.sidebarBorder,
    super.sidebarRing,
    super.custom,
  });

  const ShadTaupeColorScheme.light({
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff0c0a09),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff0c0a09),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff0c0a09),
    super.primary = const Color(0xff1d1816),
    super.primaryForeground = const Color(0xfffbfaf9),
    super.secondary = const Color(0xfff3f1f1),
    super.secondaryForeground = const Color(0xff1d1816),
    super.muted = const Color(0xfff3f1f1),
    super.mutedForeground = const Color(0xff7c6d67),
    super.accent = const Color(0xfff3f1f1),
    super.accentForeground = const Color(0xff1d1816),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xfffbfaf9),
    super.border = const Color(0xffe8e4e3),
    super.input = const Color(0xffe8e4e3),
    super.ring = const Color(0xffaba09c),
    super.selection = const Color(0x331d1816),
    super.chart1 = const Color(0xffd8d2d0),
    super.chart2 = const Color(0xff7c6d67),
    super.chart3 = const Color(0xff5b4f4b),
    super.chart4 = const Color(0xff473c39),
    super.chart5 = const Color(0xff2b2422),
    super.sidebar = const Color(0xfffbfaf9),
    super.sidebarForeground = const Color(0xff0c0a09),
    super.sidebarPrimary = const Color(0xff1d1816),
    super.sidebarPrimaryForeground = const Color(0xfffbfaf9),
    super.sidebarAccent = const Color(0xfff3f1f1),
    super.sidebarAccentForeground = const Color(0xff1d1816),
    super.sidebarBorder = const Color(0xffe8e4e3),
    super.sidebarRing = const Color(0xffaba09c),
    super.custom,
  });

  const ShadTaupeColorScheme.dark({
    super.background = const Color(0xff0c0a09),
    super.foreground = const Color(0xfffbfaf9),
    super.card = const Color(0xff1d1816),
    super.cardForeground = const Color(0xfffbfaf9),
    super.popover = const Color(0xff1d1816),
    super.popoverForeground = const Color(0xfffbfaf9),
    super.primary = const Color(0xffe8e4e3),
    super.primaryForeground = const Color(0xff1d1816),
    super.secondary = const Color(0xff2b2422),
    super.secondaryForeground = const Color(0xfffbfaf9),
    super.muted = const Color(0xff2b2422),
    super.mutedForeground = const Color(0xffaba09c),
    super.accent = const Color(0xff2b2422),
    super.accentForeground = const Color(0xfffbfaf9),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff1d1816),
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff7c6d67),
    super.selection = const Color(0x33e8e4e3),
    super.chart1 = const Color(0xffd8d2d0),
    super.chart2 = const Color(0xff7c6d67),
    super.chart3 = const Color(0xff5b4f4b),
    super.chart4 = const Color(0xff473c39),
    super.chart5 = const Color(0xff2b2422),
    super.sidebar = const Color(0xff1d1816),
    super.sidebarForeground = const Color(0xfffbfaf9),
    super.sidebarPrimary = const Color(0xff1447e6),
    super.sidebarPrimaryForeground = const Color(0xfffbfaf9),
    super.sidebarAccent = const Color(0xff2b2422),
    super.sidebarAccentForeground = const Color(0xfffbfaf9),
    super.sidebarBorder = const Color(0x1affffff),
    super.sidebarRing = const Color(0xff7c6d67),
    super.custom,
  });
}
