import 'package:flutter/widgets.dart';
import 'package:shad/src/theme/color_scheme/base.dart';

/// The shadcn/ui `zinc` colour scheme.
///
/// Generated from shadcn/ui's `registry/themes.ts`, converting each OKLCH
/// value to sRGB.
@immutable
class ShadZincColorScheme extends ShadColorScheme {
  const ShadZincColorScheme({
    required super.background,
    required super.foreground,
    required super.card,
    required super.cardForeground,
    required super.popover,
    required super.popoverForeground,
    required super.primary,
    required super.primaryForeground,
    required super.secondary,
    required super.secondaryForeground,
    required super.muted,
    required super.mutedForeground,
    required super.accent,
    required super.accentForeground,
    required super.destructive,
    required super.destructiveForeground,
    required super.border,
    required super.input,
    required super.ring,
    required super.selection,
    super.chart1,
    super.chart2,
    super.chart3,
    super.chart4,
    super.chart5,
    super.sidebar,
    super.sidebarForeground,
    super.sidebarPrimary,
    super.sidebarPrimaryForeground,
    super.sidebarAccent,
    super.sidebarAccentForeground,
    super.sidebarBorder,
    super.sidebarRing,
    super.custom,
  });

  const ShadZincColorScheme.light({
    super.background = const Color(0xffffffff),
    super.foreground = const Color(0xff09090b),
    super.card = const Color(0xffffffff),
    super.cardForeground = const Color(0xff09090b),
    super.popover = const Color(0xffffffff),
    super.popoverForeground = const Color(0xff09090b),
    super.primary = const Color(0xff18181b),
    super.primaryForeground = const Color(0xfffafafa),
    super.secondary = const Color(0xfff4f4f5),
    super.secondaryForeground = const Color(0xff18181b),
    super.muted = const Color(0xfff4f4f5),
    super.mutedForeground = const Color(0xff71717b),
    super.accent = const Color(0xfff4f4f5),
    super.accentForeground = const Color(0xff18181b),
    super.destructive = const Color(0xffe7000b),
    super.destructiveForeground = const Color(0xfffafafa),
    super.border = const Color(0xffe4e4e7),
    super.input = const Color(0xffe4e4e7),
    super.ring = const Color(0xff9f9fa9),
    super.selection = const Color(0x3318181b),
    super.chart1 = const Color(0xffd4d4d8),
    super.chart2 = const Color(0xff71717b),
    super.chart3 = const Color(0xff52525c),
    super.chart4 = const Color(0xff3f3f46),
    super.chart5 = const Color(0xff27272a),
    super.sidebar = const Color(0xfffafafa),
    super.sidebarForeground = const Color(0xff09090b),
    super.sidebarPrimary = const Color(0xff18181b),
    super.sidebarPrimaryForeground = const Color(0xfffafafa),
    super.sidebarAccent = const Color(0xfff4f4f5),
    super.sidebarAccentForeground = const Color(0xff18181b),
    super.sidebarBorder = const Color(0xffe4e4e7),
    super.sidebarRing = const Color(0xff9f9fa9),
    super.custom,
  });

  const ShadZincColorScheme.dark({
    super.background = const Color(0xff09090b),
    super.foreground = const Color(0xfffafafa),
    super.card = const Color(0xff18181b),
    super.cardForeground = const Color(0xfffafafa),
    super.popover = const Color(0xff18181b),
    super.popoverForeground = const Color(0xfffafafa),
    super.primary = const Color(0xffe4e4e7),
    super.primaryForeground = const Color(0xff18181b),
    super.secondary = const Color(0xff27272a),
    super.secondaryForeground = const Color(0xfffafafa),
    super.muted = const Color(0xff27272a),
    super.mutedForeground = const Color(0xff9f9fa9),
    super.accent = const Color(0xff27272a),
    super.accentForeground = const Color(0xfffafafa),
    super.destructive = const Color(0xffff6467),
    super.destructiveForeground = const Color(0xff18181b),
    super.border = const Color(0x1affffff),
    super.input = const Color(0x26ffffff),
    super.ring = const Color(0xff71717b),
    super.selection = const Color(0x33e4e4e7),
    super.chart1 = const Color(0xffd4d4d8),
    super.chart2 = const Color(0xff71717b),
    super.chart3 = const Color(0xff52525c),
    super.chart4 = const Color(0xff3f3f46),
    super.chart5 = const Color(0xff27272a),
    super.sidebar = const Color(0xff18181b),
    super.sidebarForeground = const Color(0xfffafafa),
    super.sidebarPrimary = const Color(0xff1447e6),
    super.sidebarPrimaryForeground = const Color(0xfffafafa),
    super.sidebarAccent = const Color(0xff27272a),
    super.sidebarAccentForeground = const Color(0xfffafafa),
    super.sidebarBorder = const Color(0x1affffff),
    super.sidebarRing = const Color(0xff71717b),
    super.custom,
  });
}
